# Generated by Django 4.2.14 on 2024-07-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_taskmodel_proj_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='tdesc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
